site_name: Lmod Log Ingestion Utility
repo_url: https://github.com/pitt-crc/lmod_tracking
theme:
  name: readthedocs
  highlightjs: true
  include_homepage_in_sidebar: true
  prev_next_buttons_location: bottom
plugins:
  - search:
  - mkdocstrings:
      custom_templates: templates
extra:
  version:
    provider: mike
nav:
  - index.md
  - installation.md
  - usage.md
  - log_formatting.md
copyright: Copyright &copy; University of Pittsburgh. All rights reserved.
